// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using UCR.ECCI.PI.ThemePark_UCR.Infrastructure.ApiClient.Client.GetStudent.Item;
namespace UCR.ECCI.PI.ThemePark_UCR.Infrastructure.ApiClient.Client.GetStudent {
    /// <summary>
    /// Builds and executes requests for operations under \get-student
    /// </summary>
    public class GetStudentRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>Gets an item from the UCR.ECCI.PI.ThemePark_UCR.Infrastructure.ApiClient.Client.getStudent.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="GetStudentItemRequestBuilder"/></returns>
        public GetStudentItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new GetStudentItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="GetStudentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetStudentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/get-student", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="GetStudentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetStudentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/get-student", rawUrl)
        {
        }
    }
}
