// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models {
    public class Level : IParsable 
    {
        /// <summary>The building property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models.Building? Building { get; set; }
#nullable restore
#else
        public UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models.Building Building { get; set; }
#endif
        /// <summary>The buildingAcronym property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public ShortName? BuildingAcronym { get; set; }
#nullable restore
#else
        public ShortName BuildingAcronym { get; set; }
#endif
        /// <summary>The campusName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public LongName? CampusName { get; set; }
#nullable restore
#else
        public LongName CampusName { get; set; }
#endif
        /// <summary>The learningSpaceCount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Counter? LearningSpaceCount { get; set; }
#nullable restore
#else
        public Counter LearningSpaceCount { get; set; }
#endif
        /// <summary>The levelId property</summary>
        public Guid? LevelId { get; set; }
        /// <summary>The levelNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Counter? LevelNumber { get; set; }
#nullable restore
#else
        public Counter LevelNumber { get; set; }
#endif
        /// <summary>The siteName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public MediumName? SiteName { get; set; }
#nullable restore
#else
        public MediumName SiteName { get; set; }
#endif
        /// <summary>The sizeX property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Size? SizeX { get; set; }
#nullable restore
#else
        public Size SizeX { get; set; }
#endif
        /// <summary>The sizeY property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Size? SizeY { get; set; }
#nullable restore
#else
        public Size SizeY { get; set; }
#endif
        /// <summary>The sizeZ property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Size? SizeZ { get; set; }
#nullable restore
#else
        public Size SizeZ { get; set; }
#endif
        /// <summary>The universityName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public LongName? UniversityName { get; set; }
#nullable restore
#else
        public LongName UniversityName { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="Level"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Level CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Level();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"building", n => { Building = n.GetObjectValue<UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models.Building>(UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models.Building.CreateFromDiscriminatorValue); } },
                {"buildingAcronym", n => { BuildingAcronym = n.GetObjectValue<ShortName>(ShortName.CreateFromDiscriminatorValue); } },
                {"campusName", n => { CampusName = n.GetObjectValue<LongName>(LongName.CreateFromDiscriminatorValue); } },
                {"learningSpaceCount", n => { LearningSpaceCount = n.GetObjectValue<Counter>(Counter.CreateFromDiscriminatorValue); } },
                {"levelId", n => { LevelId = n.GetGuidValue(); } },
                {"levelNumber", n => { LevelNumber = n.GetObjectValue<Counter>(Counter.CreateFromDiscriminatorValue); } },
                {"siteName", n => { SiteName = n.GetObjectValue<MediumName>(MediumName.CreateFromDiscriminatorValue); } },
                {"sizeX", n => { SizeX = n.GetObjectValue<Size>(Size.CreateFromDiscriminatorValue); } },
                {"sizeY", n => { SizeY = n.GetObjectValue<Size>(Size.CreateFromDiscriminatorValue); } },
                {"sizeZ", n => { SizeZ = n.GetObjectValue<Size>(Size.CreateFromDiscriminatorValue); } },
                {"universityName", n => { UniversityName = n.GetObjectValue<LongName>(LongName.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models.Building>("building", Building);
            writer.WriteObjectValue<ShortName>("buildingAcronym", BuildingAcronym);
            writer.WriteObjectValue<LongName>("campusName", CampusName);
            writer.WriteObjectValue<Counter>("learningSpaceCount", LearningSpaceCount);
            writer.WriteGuidValue("levelId", LevelId);
            writer.WriteObjectValue<Counter>("levelNumber", LevelNumber);
            writer.WriteObjectValue<MediumName>("siteName", SiteName);
            writer.WriteObjectValue<Size>("sizeX", SizeX);
            writer.WriteObjectValue<Size>("sizeY", SizeY);
            writer.WriteObjectValue<Size>("sizeZ", SizeZ);
            writer.WriteObjectValue<LongName>("universityName", UniversityName);
        }
    }
}
