// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models {
    public class Persons : IParsable 
    {
        /// <summary>The birthDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public BirthDateValueObject? BirthDate { get; set; }
#nullable restore
#else
        public BirthDateValueObject BirthDate { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public EmailValueObject? Email { get; set; }
#nullable restore
#else
        public EmailValueObject Email { get; set; }
#endif
        /// <summary>The firstLastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UserNameValueObject? FirstLastName { get; set; }
#nullable restore
#else
        public UserNameValueObject FirstLastName { get; set; }
#endif
        /// <summary>The firstName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UserNameValueObject? FirstName { get; set; }
#nullable restore
#else
        public UserNameValueObject FirstName { get; set; }
#endif
        /// <summary>The middleName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UserNameValueObject? MiddleName { get; set; }
#nullable restore
#else
        public UserNameValueObject MiddleName { get; set; }
#endif
        /// <summary>The personId property</summary>
        public Guid? PersonId { get; set; }
        /// <summary>The phoneNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PhoneValueObject? PhoneNumber { get; set; }
#nullable restore
#else
        public PhoneValueObject PhoneNumber { get; set; }
#endif
        /// <summary>The secondLastName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UserNameValueObject? SecondLastName { get; set; }
#nullable restore
#else
        public UserNameValueObject SecondLastName { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models.User? User { get; set; }
#nullable restore
#else
        public UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models.User User { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="Persons"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Persons CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Persons();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"birthDate", n => { BirthDate = n.GetObjectValue<BirthDateValueObject>(BirthDateValueObject.CreateFromDiscriminatorValue); } },
                {"email", n => { Email = n.GetObjectValue<EmailValueObject>(EmailValueObject.CreateFromDiscriminatorValue); } },
                {"firstLastName", n => { FirstLastName = n.GetObjectValue<UserNameValueObject>(UserNameValueObject.CreateFromDiscriminatorValue); } },
                {"firstName", n => { FirstName = n.GetObjectValue<UserNameValueObject>(UserNameValueObject.CreateFromDiscriminatorValue); } },
                {"middleName", n => { MiddleName = n.GetObjectValue<UserNameValueObject>(UserNameValueObject.CreateFromDiscriminatorValue); } },
                {"personId", n => { PersonId = n.GetGuidValue(); } },
                {"phoneNumber", n => { PhoneNumber = n.GetObjectValue<PhoneValueObject>(PhoneValueObject.CreateFromDiscriminatorValue); } },
                {"secondLastName", n => { SecondLastName = n.GetObjectValue<UserNameValueObject>(UserNameValueObject.CreateFromDiscriminatorValue); } },
                {"user", n => { User = n.GetObjectValue<UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models.User>(UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models.User.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<BirthDateValueObject>("birthDate", BirthDate);
            writer.WriteObjectValue<EmailValueObject>("email", Email);
            writer.WriteObjectValue<UserNameValueObject>("firstLastName", FirstLastName);
            writer.WriteObjectValue<UserNameValueObject>("firstName", FirstName);
            writer.WriteObjectValue<UserNameValueObject>("middleName", MiddleName);
            writer.WriteGuidValue("personId", PersonId);
            writer.WriteObjectValue<PhoneValueObject>("phoneNumber", PhoneNumber);
            writer.WriteObjectValue<UserNameValueObject>("secondLastName", SecondLastName);
            writer.WriteObjectValue<UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models.User>("user", User);
        }
    }
}
