// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace UCR.ECCI.IS.ExampleProject.Infrastructure.ApiClient.Client.Models {
    public class User : IParsable 
    {
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The personId property</summary>
        public Guid? PersonId { get; set; }
        /// <summary>The roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<Role>? Roles { get; set; }
#nullable restore
#else
        public List<Role> Roles { get; set; }
#endif
        /// <summary>The userId property</summary>
        public Guid? UserId { get; set; }
        /// <summary>The userNickName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UserNameValueObject? UserNickName { get; set; }
#nullable restore
#else
        public UserNameValueObject UserNickName { get; set; }
#endif
        /// <summary>The userPasswordHash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public PasswordValueObject? UserPasswordHash { get; set; }
#nullable restore
#else
        public PasswordValueObject UserPasswordHash { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="User"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static User CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new User();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"isActive", n => { IsActive = n.GetBoolValue(); } },
                {"personId", n => { PersonId = n.GetGuidValue(); } },
                {"roles", n => { Roles = n.GetCollectionOfObjectValues<Role>(Role.CreateFromDiscriminatorValue)?.ToList(); } },
                {"userId", n => { UserId = n.GetGuidValue(); } },
                {"userNickName", n => { UserNickName = n.GetObjectValue<UserNameValueObject>(UserNameValueObject.CreateFromDiscriminatorValue); } },
                {"userPasswordHash", n => { UserPasswordHash = n.GetObjectValue<PasswordValueObject>(PasswordValueObject.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteGuidValue("personId", PersonId);
            writer.WriteCollectionOfObjectValues<Role>("roles", Roles);
            writer.WriteGuidValue("userId", UserId);
            writer.WriteObjectValue<UserNameValueObject>("userNickName", UserNickName);
            writer.WriteObjectValue<PasswordValueObject>("userPasswordHash", UserPasswordHash);
        }
    }
}
