// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace UCR.ECCI.PI.ThemePark_UCR.Infrastructure.ApiClient.Client.Models {
    public class Templates : IParsable 
    {
        /// <summary>The ceilingColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public MediumName? CeilingColor { get; set; }
#nullable restore
#else
        public MediumName CeilingColor { get; set; }
#endif
        /// <summary>The floorColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public MediumName? FloorColor { get; set; }
#nullable restore
#else
        public MediumName FloorColor { get; set; }
#endif
        /// <summary>The id property</summary>
        public Guid? Id { get; set; }
        /// <summary>The sizeX property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public DoubleWrapper? SizeX { get; set; }
#nullable restore
#else
        public DoubleWrapper SizeX { get; set; }
#endif
        /// <summary>The sizeY property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public DoubleWrapper? SizeY { get; set; }
#nullable restore
#else
        public DoubleWrapper SizeY { get; set; }
#endif
        /// <summary>The sizeZ property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public DoubleWrapper? SizeZ { get; set; }
#nullable restore
#else
        public DoubleWrapper SizeZ { get; set; }
#endif
        /// <summary>The templateName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public MediumName? TemplateName { get; set; }
#nullable restore
#else
        public MediumName TemplateName { get; set; }
#endif
        /// <summary>The type property</summary>
        public Guid? Type { get; set; }
        /// <summary>The wallsColor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public MediumName? WallsColor { get; set; }
#nullable restore
#else
        public MediumName WallsColor { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="Templates"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static Templates CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new Templates();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"ceilingColor", n => { CeilingColor = n.GetObjectValue<MediumName>(MediumName.CreateFromDiscriminatorValue); } },
                {"floorColor", n => { FloorColor = n.GetObjectValue<MediumName>(MediumName.CreateFromDiscriminatorValue); } },
                {"id", n => { Id = n.GetGuidValue(); } },
                {"sizeX", n => { SizeX = n.GetObjectValue<DoubleWrapper>(DoubleWrapper.CreateFromDiscriminatorValue); } },
                {"sizeY", n => { SizeY = n.GetObjectValue<DoubleWrapper>(DoubleWrapper.CreateFromDiscriminatorValue); } },
                {"sizeZ", n => { SizeZ = n.GetObjectValue<DoubleWrapper>(DoubleWrapper.CreateFromDiscriminatorValue); } },
                {"templateName", n => { TemplateName = n.GetObjectValue<MediumName>(MediumName.CreateFromDiscriminatorValue); } },
                {"type", n => { Type = n.GetGuidValue(); } },
                {"wallsColor", n => { WallsColor = n.GetObjectValue<MediumName>(MediumName.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<MediumName>("ceilingColor", CeilingColor);
            writer.WriteObjectValue<MediumName>("floorColor", FloorColor);
            writer.WriteGuidValue("id", Id);
            writer.WriteObjectValue<DoubleWrapper>("sizeX", SizeX);
            writer.WriteObjectValue<DoubleWrapper>("sizeY", SizeY);
            writer.WriteObjectValue<DoubleWrapper>("sizeZ", SizeZ);
            writer.WriteObjectValue<MediumName>("templateName", TemplateName);
            writer.WriteGuidValue("type", Type);
            writer.WriteObjectValue<MediumName>("wallsColor", WallsColor);
        }
    }
}
