// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace UCR.ECCI.PI.ThemePark_UCR.Infrastructure.ApiClient.Client.Models {
    public class UserDto : IParsable 
    {
        /// <summary>The isActive property</summary>
        public bool? IsActive { get; set; }
        /// <summary>The personId property</summary>
        public Guid? PersonId { get; set; }
        /// <summary>The roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<RoleDto>? Roles { get; set; }
#nullable restore
#else
        public List<RoleDto> Roles { get; set; }
#endif
        /// <summary>The userId property</summary>
        public Guid? UserId { get; set; }
        /// <summary>The userNickName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserNickName { get; set; }
#nullable restore
#else
        public string UserNickName { get; set; }
#endif
        /// <summary>The userPasswordHash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserPasswordHash { get; set; }
#nullable restore
#else
        public string UserPasswordHash { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="UserDto"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static UserDto CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new UserDto();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                {"isActive", n => { IsActive = n.GetBoolValue(); } },
                {"personId", n => { PersonId = n.GetGuidValue(); } },
                {"roles", n => { Roles = n.GetCollectionOfObjectValues<RoleDto>(RoleDto.CreateFromDiscriminatorValue)?.ToList(); } },
                {"userId", n => { UserId = n.GetGuidValue(); } },
                {"userNickName", n => { UserNickName = n.GetStringValue(); } },
                {"userPasswordHash", n => { UserPasswordHash = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("isActive", IsActive);
            writer.WriteGuidValue("personId", PersonId);
            writer.WriteCollectionOfObjectValues<RoleDto>("roles", Roles);
            writer.WriteGuidValue("userId", UserId);
            writer.WriteStringValue("userNickName", UserNickName);
            writer.WriteStringValue("userPasswordHash", UserPasswordHash);
        }
    }
}
