// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using UCR.ECCI.PI.ThemePark_UCR.Infrastructure.ApiClient.Client.GetProfessor.Item;
namespace UCR.ECCI.PI.ThemePark_UCR.Infrastructure.ApiClient.Client.GetProfessor {
    /// <summary>
    /// Builds and executes requests for operations under \get-professor
    /// </summary>
    public class GetProfessorRequestBuilder : BaseRequestBuilder 
    {
        /// <summary>Gets an item from the UCR.ECCI.PI.ThemePark_UCR.Infrastructure.ApiClient.Client.getProfessor.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="GetProfessorItemRequestBuilder"/></returns>
        public GetProfessorItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new GetProfessorItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="GetProfessorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetProfessorRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/get-professor", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="GetProfessorRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GetProfessorRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/get-professor", rawUrl)
        {
        }
    }
}
