/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

/*
Post-deployment script for ThemePark.[Level]
*/
MERGE INTO ThemePark.[Level] AS TARGET
USING (VALUES
    (/*LevelId*/            'b43f7220-f53f-426b-a588-6f500a845a14', 
    /*BuildingId*/          '2482b77a-2337-4020-835a-31523c13bee7',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'IF', 
    /*LevelNumber*/         1, 
    /*SizeX*/               11, 
    /*SizeY*/               11, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#FF0000',
    /*FloorColor*/          '#00FF00',
    /*CeilingColor*/        '#0000FF',
    /*LearningSpaceCount*/  3),

    (/*LevelId*/            '533241a8-6c7d-4b31-af30-285e5bdd25d1', 
    /*BuildingId*/          '2482b77a-2337-4020-835a-31523c13bee7',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'IF', 
    /*LevelNumber*/         2, 
    /*SizeX*/               22, 
    /*SizeY*/               22, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#110000',
    /*FloorColor*/          '#001100',
    /*CeilingColor*/        '#000011',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '4738bdac-5571-41a1-84bb-1e7018b20a3c', 
    /*BuildingId*/          '2482b77a-2337-4020-835a-31523c13bee7',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'IF', 
    /*LevelNumber*/         3, 
    /*SizeX*/               33, 
    /*SizeY*/               33, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#002200',
    /*FloorColor*/          '#220000',
    /*CeilingColor*/        '#002200',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '698a759c-b9b8-49ab-b2a9-31396dbf4550', 
    /*BuildingId*/          '4f576f1b-3125-4352-8055-e63e8f9359c8',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'IF Anexo', 
    /*LevelNumber*/         1, 
    /*SizeX*/               10, 
    /*SizeY*/               10, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#003300',
    /*FloorColor*/          '#330000',
    /*CeilingColor*/        '#003300',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '2eac7d63-a4e1-48c8-8782-ef9e91a5c2fd', 
    /*BuildingId*/          '4f576f1b-3125-4352-8055-e63e8f9359c8',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'IF Anexo', 
    /*LevelNumber*/         2, 
    /*SizeX*/               20, 
    /*SizeY*/               20, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#004400',
    /*FloorColor*/          '#440000',
    /*CeilingColor*/        '#000044',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            'c58e8cda-4c6a-495d-90f7-1b1801c8ade2', 
    /*BuildingId*/          '4f576f1b-3125-4352-8055-e63e8f9359c8',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'IF Anexo', 
    /*LevelNumber*/         3, 
    /*SizeX*/               30, 
    /*SizeY*/               30, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#005500',
    /*FloorColor*/          '#550000',
    /*CeilingColor*/        '#000055',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '8e451830-5e94-40f1-9dac-aa6c34368611', 
    /*BuildingId*/          '4f576f1b-3125-4352-8055-e63e8f9359c8',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'IF Anexo', 
    /*LevelNumber*/         4, 
    /*SizeX*/               40, 
    /*SizeY*/               40, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#006600',
    /*FloorColor*/          '#660000',
    /*CeilingColor*/        '#000066',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            'f1a35782-e75b-47ea-965e-bf8cec1161c8', 
    /*BuildingId*/          '4f576f1b-3125-4352-8055-e63e8f9359c8',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'IF Anexo', 
    /*LevelNumber*/         5, 
    /*SizeX*/               50, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#007700',
    /*FloorColor*/          '#770000',
    /*CeilingColor*/        '#000077',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '737fb47c-69e7-4bd4-97f3-1626b62269cf', 
    /*BuildingId*/          '4f576f1b-3125-4352-8055-e63e8f9359c8',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'IF Anexo', 
    /*LevelNumber*/         6, 
    /*SizeX*/               60, 
    /*SizeY*/               60, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#008800',
    /*FloorColor*/          '#880000',
    /*CeilingColor*/        '#000088',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '930d7725-6acb-43c3-b3ce-c6a16fd28417', 
    /*BuildingId*/          'aa1ed5d4-6308-4a5d-9101-5fc4837e5003',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'FM', 
    /*LevelNumber*/         1, 
    /*SizeX*/               11, 
    /*SizeY*/               11, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#009900',
    /*FloorColor*/          '#990000',
    /*CeilingColor*/        '#000099',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '955b6b52-1f80-41f8-a642-19c088ccfd94', 
    /*BuildingId*/          'aa1ed5d4-6308-4a5d-9101-5fc4837e5003',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'FM', 
    /*LevelNumber*/         2, 
    /*SizeX*/               22, 
    /*SizeY*/               22, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#00AA00',
    /*FloorColor*/          '#AA0000',
    /*CeilingColor*/        '#0000AA',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '8aeda675-b517-45ac-98d6-c7b71df9d741', 
    /*BuildingId*/          'aa1ed5d4-6308-4a5d-9101-5fc4837e5003',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'FM', 
    /*LevelNumber*/         3, 
    /*SizeX*/               33, 
    /*SizeY*/               33, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#00BB00',
    /*FloorColor*/          '#BB0000',
    /*CeilingColor*/        '#0000BB',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            'baf9a243-d7ce-4b60-a39e-04fe205a325a', 
    /*BuildingId*/          'aa1ed5d4-6308-4a5d-9101-5fc4837e5003',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'FM', 
    /*LevelNumber*/         4, 
    /*SizeX*/               44, 
    /*SizeY*/               44, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#00CC00',
    /*FloorColor*/          '#CC0000',
    /*CeilingColor*/        '#0000CC',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '2c71657c-06fc-40ef-8999-3d663757965e', 
    /*BuildingId*/          'ca471188-a888-4f00-8262-8dc3b1f8784f',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'GE', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#00DD00',
    /*FloorColor*/          '#DD0000',
    /*CeilingColor*/        '#0000DD',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '6391b1cc-5640-49d5-9bec-61e4a1101a90', 
    /*BuildingId*/          'c6c3a1e6-1625-484b-a9fd-2d36224cd56f',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'ME', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#00EE00',
    /*FloorColor*/          '#EE0000',
    /*CeilingColor*/        '#0000EE',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            'a90059f3-5253-4ea4-b4ee-04af135e839d', 
    /*BuildingId*/          '5462b59a-cfcb-4817-9c06-3374fb885a35',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'AD', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#11FF00',
    /*FloorColor*/          '#FF1100',
    /*CeilingColor*/        '#0011FF',
    /*LearningSpaceCount*/  2),

    (/*LevelId*/            '61de8e2d-f92a-45b9-a22f-2b63ae460900', 
    /*BuildingId*/          '7e717780-3f1b-4001-8f72-2db507d48013',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'AM', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#22FF00',
    /*FloorColor*/          '#FF2200',
    /*CeilingColor*/        '#0022FF',
    /*LearningSpaceCount*/  2),

    (/*LevelId*/            'c022a684-fbca-4f0a-aa1c-1aaeb45c6723', 
    /*BuildingId*/          '5a327f35-05d0-48e4-a295-c46d46d72a38',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'AU', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#33FF00',
    /*FloorColor*/          '#FF3300',
    /*CeilingColor*/        '#0033FF',
    /*LearningSpaceCount*/  2),

    (/*LevelId*/            'aac4addb-9a66-4bc8-a67a-39e375047181', 
    /*BuildingId*/          '53a9ab70-d44d-40f9-8627-7bfb6bb55a72',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'BL', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#44FF00',
    /*FloorColor*/          '#FF4400',
    /*CeilingColor*/        '#0044FF',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '21732f83-5424-4109-a45d-88012108de2b', 
    /*BuildingId*/          '41ab2eaf-cde7-4e02-8ccb-409c5383d32f',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'DE', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#55FF00',
    /*FloorColor*/          '#FF5500',
    /*CeilingColor*/        '#0055FF',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '1164be71-359b-48e1-add3-9a55770271b0', 
    /*BuildingId*/          'b76852ce-79df-48f5-8f1c-976edb2b4ef5',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 2', 
    /*BuildingAcronym*/     'CI', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#66FF00',
    /*FloorColor*/          '#FF6600',
    /*CeilingColor*/        '#0066FF',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '677ad01f-87f4-4804-8700-84f979afc56e', 
    /*BuildingId*/          '7bf22678-9dd2-40b7-b0cd-dc5dbadf3fce',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Finca 2', 
    /*BuildingAcronym*/     'CS', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#77FF00',
    /*FloorColor*/          '#FF7700',
    /*CeilingColor*/        '#0077FF',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '6c10a4c4-1e0e-4bd6-b37b-acdc78e82406', 
    /*BuildingId*/          '9252b42e-411c-404d-8e56-2a3905466eaa',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede Rodrigo Facio', 
    /*SiteName*/            'Deportivas', 
    /*BuildingAcronym*/     'OD', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#88FF00',
    /*FloorColor*/          '#FF8800',
    /*CeilingColor*/        '#0088FF',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            'd92d7733-62ff-4623-924e-a987098adc55', 
    /*BuildingId*/          'b65e22ac-1152-4655-ad5e-92de255c74dd',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede de Occidente', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'QU', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#99FF00',
    /*FloorColor*/          '#FF9900',
    /*CeilingColor*/        '#0099FF',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '4afe2369-6c0a-487c-b3ab-7e8e59117606', 
    /*BuildingId*/          '2bd16798-3e5a-4aa3-8c33-ce3ac20bc387',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede del Atlantico', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'TA', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#AAFF00',
    /*FloorColor*/          '#FFAA00',
    /*CeilingColor*/        '#00AAFF',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '4e48057d-80ec-48d3-8f5f-7eb4b609a644', 
    /*BuildingId*/          'a959d836-3112-43df-a72e-5167473a6e88',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede del Pacifico', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'TS', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#BBFF00',
    /*FloorColor*/          '#FFBB00',
    /*CeilingColor*/        '#00BBFF',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            'b6c6e2a7-18eb-4dc5-ae51-b84c672d6b24', 
    /*BuildingId*/          'de9c77ce-6d07-43ad-ac75-175193909594',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede del Sur', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'MI', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#CCFF00',
    /*FloorColor*/          '#FFCC00',
    /*CeilingColor*/        '#00CCFF',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '341a804f-df67-4b95-9222-ccfb17291531', 
    /*BuildingId*/          '6ef3c4c1-2bf2-4036-b605-1a19f06702ce',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede del Caribe', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'LE', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#DDFF00',
    /*FloorColor*/          '#FFDD00',
    /*CeilingColor*/        '#00DDFF',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '1b73460c-15bc-4dcf-b1c4-682f4d6f37b2', 
    /*BuildingId*/          'b9c929b2-f6c8-4941-99fe-e30215e17a58',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede de Guanacaste', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'FA', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#EEFF00',
    /*FloorColor*/          '#FFEE00',
    /*CeilingColor*/        '#00EEFF',
    /*LearningSpaceCount*/  0),

    (/*LevelId*/            '4e23d620-c2fd-45a4-8c8f-47f01032ff67', 
    /*BuildingId*/          '94e6cd70-d9fa-4cbf-a8b7-50194f7ceb5e',
    /*UniversityName*/      'Universidad de Costa Rica', 
    /*CampusName*/          'Sede del Este', 
    /*SiteName*/            'Finca 1', 
    /*BuildingAcronym*/     'EG', 
    /*LevelNumber*/         1, 
    /*SizeX*/               20, 
    /*SizeY*/               50, 
    /*SizeZ*/               3, 
    /*WallsColor*/          '#FF00FF',
    /*FloorColor*/          '#FF00FF',
    /*CeilingColor*/        '#FF00FF',
    /*LearningSpaceCount*/  0)
)
AS SOURCE (
    LevelId,
    BuildingId,
    UniversityName,
    CampusName,
    SiteName,
    BuildingAcronym,
    LevelNumber,
    SizeX,
    SizeY,
    SizeZ,
    WallsColor,
    FloorColor,
    CeilingColor,
    LearningSpaceCount
)
ON
    TARGET.LevelId = SOURCE.LevelId
WHEN NOT MATCHED THEN
    INSERT (
        LevelId,
        BuildingId,
        UniversityName,
        CampusName,
        SiteName,
        BuildingAcronym,
        LevelNumber,
        SizeX,
        SizeY,
        SizeZ,
        WallsColor,
        FloorColor,
        CeilingColor,
        LearningSpaceCount
    )
    VALUES (
        SOURCE.LevelId,
        SOURCE.BuildingId,
        SOURCE.UniversityName,
        SOURCE.CampusName,
        SOURCE.SiteName,
        SOURCE.BuildingAcronym,
        SOURCE.LevelNumber,
        SOURCE.SizeX,
        SOURCE.SizeY,
        SOURCE.SizeZ,
        SOURCE.WallsColor,
        SOURCE.FloorColor,
        SOURCE.CeilingColor,
        SOURCE.LearningSpaceCount
    )
WHEN MATCHED THEN
    UPDATE SET
        BuildingId = SOURCE.BuildingId,
        UniversityName = SOURCE.UniversityName,
        CampusName = SOURCE.CampusName,
        SiteName = SOURCE.SiteName,
        BuildingAcronym = SOURCE.BuildingAcronym,
        LevelNumber = SOURCE.LevelNumber,
        SizeX = SOURCE.SizeX,
        SizeY = SOURCE.SizeY,
        SizeZ = SOURCE.SizeZ,
        WallsColor = SOURCE.WallsColor,
        FloorColor = SOURCE.FloorColor,
        CeilingColor = SOURCE.CeilingColor,
        LearningSpaceCount = SOURCE.LearningSpaceCount;
