/*
Post-deployment script for ThemePark.Building
*/
MERGE INTO ThemePark.Building AS TARGET
USING (VALUES
    (/*BuildingId*/     '2482b77a-2337-4020-835a-31523c13bee7',
    /*SiteId*/          'd38bf38e-93f5-4452-9bd8-a78ffd4e16a5',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'IF', 
    /*BuildingName*/    'Informatica', 
    /*CenterX*/         110, 
    /*CenterY*/         180, 
    /*Rotation*/        20, 
    /*Length*/          30, 
    /*Width*/           20, 
    /*Height*/          3,
    /*WallsColor*/      '#FF0000',
    /*RoofColor*/       '#00FF00',
    /*LevelCount*/      3),

    (/*BuildingId*/     '4f576f1b-3125-4352-8055-e63e8f9359c8',
    /*SiteId*/          'd38bf38e-93f5-4452-9bd8-a78ffd4e16a5',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'IF Anexo', 
    /*BuildingName*/    'Informatica Anexo', 
    /*CenterX*/         110, 
    /*CenterY*/         380, 
    /*Rotation*/        45, 
    /*Length*/          50, 
    /*Width*/           50, 
    /*Height*/          6,
    /*WallsColor*/      '#AA0000',
    /*RoofColor*/       '#00AA00',
    /*LevelCount*/      6),

    (/*BuildingId*/     'aa1ed5d4-6308-4a5d-9101-5fc4837e5003',
    /*SiteId*/          'd38bf38e-93f5-4452-9bd8-a78ffd4e16a5',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'FM', 
    /*BuildingName*/    'Fisica Matematica', 
    /*CenterX*/         80, 
    /*CenterY*/         570, 
    /*Rotation*/        170, 
    /*Length*/          40, 
    /*Width*/           40, 
    /*Height*/          4,
    /*WallsColor*/      '#0033CC',
    /*RoofColor*/       '#00CC33',
    /*LevelCount*/      4),

    (/*BuildingId*/     'ca471188-a888-4f00-8262-8dc3b1f8784f',
    /*SiteId*/          'd38bf38e-93f5-4452-9bd8-a78ffd4e16a5',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'GE', 
    /*BuildingName*/    'Geologia', 
    /*CenterX*/         320, 
    /*CenterY*/         100, 
    /*Rotation*/        200, 
    /*Length*/          45, 
    /*Width*/           45, 
    /*Height*/          1,
    /*WallsColor*/      '#FFCC00',
    /*RoofColor*/       '#CCFF00',
    /*LevelCount*/      1),

    (/*BuildingId*/     'c6c3a1e6-1625-484b-a9fd-2d36224cd56f',
    /*SiteId*/          'd38bf38e-93f5-4452-9bd8-a78ffd4e16a5',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'ME', 
    /*BuildingName*/    'Medicina', 
    /*CenterX*/         330, 
    /*CenterY*/         290, 
    /*Rotation*/        300, 
    /*Length*/          20, 
    /*Width*/           20, 
    /*Height*/          1,
    /*WallsColor*/      '#00CC66',
    /*RoofColor*/       '#CC0056',
    /*LevelCount*/      1),

    (/*BuildingId*/     '5462b59a-cfcb-4817-9c06-3374fb885a35',
    /*SiteId*/          'd38bf38e-93f5-4452-9bd8-a78ffd4e16a5',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'AD', 
    /*BuildingName*/    'Artes Dramaticas', 
    /*CenterX*/         310, 
    /*CenterY*/         500, 
    /*Rotation*/        270, 
    /*Length*/          30, 
    /*Width*/           30,
    /*Height*/          1,
    /*WallsColor*/      '#FF00CC',
    /*RoofColor*/       '#00FFCC', 
    /*LevelCount*/      1),

    (/*BuildingId*/     '7e717780-3f1b-4001-8f72-2db507d48013',
    /*SiteId*/          'd38bf38e-93f5-4452-9bd8-a78ffd4e16a5',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'AM', 
    /*BuildingName*/    'Artes Musicales', 
    /*CenterX*/         520, 
    /*CenterY*/         190, 
    /*Rotation*/        45, 
    /*Length*/          40, 
    /*Width*/           40, 
    /*Height*/          1,
    /*WallsColor*/      '#FF00FF',
    /*RoofColor*/       '#00FFFF',
    /*LevelCount*/      1),

    (/*BuildingId*/     '5a327f35-05d0-48e4-a295-c46d46d72a38',
    /*SiteId*/          'd38bf38e-93f5-4452-9bd8-a78ffd4e16a5',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'AU', 
    /*BuildingName*/    'Aulas', 
    /*CenterX*/         530, 
    /*CenterY*/         380, 
    /*Rotation*/        90, 
    /*Length*/          20, 
    /*Width*/           20, 
    /*Height*/          1,
    /*WallsColor*/      '#00FF44',
    /*RoofColor*/       '#44FF00',
    /*LevelCount*/      1),

    (/*BuildingId*/     '53a9ab70-d44d-40f9-8627-7bfb6bb55a72',
    /*SiteId*/          'd38bf38e-93f5-4452-9bd8-a78ffd4e16a5',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'BL', 
    /*BuildingName*/    'Bibliotecologaa', 
    /*CenterX*/         500, 
    /*CenterY*/         510, 
    /*Rotation*/        50, 
    /*Length*/          40, 
    /*Width*/           30,
    /*Height*/          1,
    /*WallsColor*/      '#AA7700',
    /*RoofColor*/       '#77AA00',
    /*LevelCount*/      1),

    (/*BuildingId*/     '41ab2eaf-cde7-4e02-8ccb-409c5383d32f',
    /*SiteId*/          'd38bf38e-93f5-4452-9bd8-a78ffd4e16a5',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'DE', 
    /*BuildingName*/    'Derecho', 
    /*CenterX*/         50, 
    /*CenterY*/         650, 
    /*Rotation*/        58, 
    /*Length*/          10, 
    /*Width*/           10, 
    /*Height*/          1,
    /*WallsColor*/      '#0033CC',
    /*RoofColor*/       '#33CC00',
    /*LevelCount*/      1),

    (/*BuildingId*/     'b76852ce-79df-48f5-8f1c-976edb2b4ef5',
    /*SiteId*/          '86815ee2-c5c0-43ca-bdbc-240e7e939c1e',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 2', 
    /*BuildingAcronym*/ 'CI', 
    /*BuildingName*/    'Ciencias', 
    /*CenterX*/         100, 
    /*CenterY*/         100, 
    /*Rotation*/        45, 
    /*Length*/          20, 
    /*Width*/           20,
    /*Height*/          1,
    /*WallsColor*/      '#FF0011',
    /*RoofColor*/       '#11FF00',
    /*LevelCount*/      1),

    (/*BuildingId*/     '7bf22678-9dd2-40b7-b0cd-dc5dbadf3fce',
    /*SiteId*/          '86815ee2-c5c0-43ca-bdbc-240e7e939c1e',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Finca 2', 
    /*BuildingAcronym*/ 'CS', 
    /*BuildingName*/    'Ciencias Sociales', 
    /*CenterX*/         100, 
    /*CenterY*/         100, 
    /*Rotation*/        45, 
    /*Length*/          20, 
    /*Width*/           20, 
    /*Height*/          1,
    /*WallsColor*/      '#661100',
    /*RoofColor*/       '#116611',
    /*LevelCount*/      1),

    (/*BuildingId*/     '9252b42e-411c-404d-8e56-2a3905466eaa',
    /*SiteId*/          'f4887842-cc5d-4f45-9f98-b863398eacdf',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede Rodrigo Facio', 
    /*SiteName*/        'Deportivas', 
    /*BuildingAcronym*/ 'OD', 
    /*BuildingName*/    'Odontología', 
    /*CenterX*/         100, 
    /*CenterY*/         100, 
    /*Rotation*/        45, 
    /*Length*/          20, 
    /*Width*/           20, 
    /*Height*/          1,
    /*WallsColor*/      '#776600',
    /*RoofColor*/       '#667700',
    /*LevelCount*/      1),

    (/*BuildingId*/     'b65e22ac-1152-4655-ad5e-92de255c74dd',
    /*SiteId*/          'a940b8bc-febe-44bb-9f16-d1822f901028',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede de Occidente', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'QU', 
    /*BuildingName*/    'Química', 
    /*CenterX*/         100, 
    /*CenterY*/         100, 
    /*Rotation*/        45, 
    /*Length*/          20, 
    /*Width*/           20, 
    /*Height*/          1,
    /*WallsColor*/      '#004455',
    /*RoofColor*/       '#450044',
    /*LevelCount*/      1),

    (/*BuildingId*/     '2bd16798-3e5a-4aa3-8c33-ce3ac20bc387',
    /*SiteId*/          '593e53e3-e60a-4666-8737-0c11d8dc402b',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede del Atlantico', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'TA', 
    /*BuildingName*/    'Tecnología de Alimentos', 
    /*CenterX*/         100, 
    /*CenterY*/         100, 
    /*Rotation*/        45, 
    /*Length*/          20, 
    /*Width*/           20, 
    /*Height*/          1,
    /*WallsColor*/      '#4444FF',
    /*RoofColor*/       '#44FF11',
    /*LevelCount*/      1),

    (/*BuildingId*/     'a959d836-3112-43df-a72e-5167473a6e88',
    /*SiteId*/          'cb5da788-5ac3-44dc-9125-3b15abbc2ee5',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede del Pacifico', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'TS', 
    /*BuildingName*/    'Tecnologías en Salud', 
    /*CenterX*/         100, 
    /*CenterY*/         100, 
    /*Rotation*/        45, 
    /*Length*/          20, 
    /*Width*/           20, 
    /*Height*/          1,
    /*WallsColor*/      '#554433',
    /*RoofColor*/       '#33FF44',
    /*LevelCount*/      1),

    (/*BuildingId*/     'de9c77ce-6d07-43ad-ac75-175193909594',
    /*SiteId*/          '0982dc91-7392-492b-8c23-a0a45b8a6428',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede del Sur', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'MI', 
    /*BuildingName*/    'Microbiología', 
    /*CenterX*/         100, 
    /*CenterY*/         100, 
    /*Rotation*/        45, 
    /*Length*/          20, 
    /*Width*/           20, 
    /*Height*/          1,
    /*WallsColor*/      '#FF5544',
    /*RoofColor*/       '#44FF33',
    /*LevelCount*/      1),

    (/*BuildingId*/     '6ef3c4c1-2bf2-4036-b605-1a19f06702ce',
    /*SiteId*/          '2dcb1f25-25c1-4b4f-a382-c8eae72f1639',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede del Caribe', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'LE', 
    /*BuildingName*/    'Letras', 
    /*CenterX*/         100, 
    /*CenterY*/         100, 
    /*Rotation*/        45, 
    /*Length*/          20, 
    /*Width*/           20, 
    /*Height*/          1,
    /*WallsColor*/      '#114466',
    /*RoofColor*/       '#66FF44',
    /*LevelCount*/      1),

    (/*BuildingId*/     'b9c929b2-f6c8-4941-99fe-e30215e17a58',
    /*SiteId*/          '4ac4839f-a010-4a99-b645-ce37df0b7354',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede de Guanacaste', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'FA', 
    /*BuildingName*/    'Farmacia', 
    /*CenterX*/         100, 
    /*CenterY*/         100, 
    /*Rotation*/        45, 
    /*Length*/          20, 
    /*Width*/           20, 
    /*Height*/          1,
    /*WallsColor*/      '#FF1144',
    /*RoofColor*/       '#44FF66',
    /*LevelCount*/      1),

    (/*BuildingId*/     '94e6cd70-d9fa-4cbf-a8b7-50194f7ceb5e',
    /*SiteId*/          'abb6c112-198a-40bf-b8fb-a326b455bf55',
    /*UniversityName*/  'Universidad de Costa Rica', 
    /*CampusName*/      'Sede del Este', 
    /*SiteName*/        'Finca 1', 
    /*BuildingAcronym*/ 'EG', 
    /*BuildingName*/    'Estudios Generales', 
    /*CenterX*/         100, 
    /*CenterY*/         100, 
    /*Rotation*/        45, 
    /*Length*/          20, 
    /*Width*/           20, 
    /*Height*/          1,
    /*WallsColor*/      '#0230FF',
    /*RoofColor*/       '#30FF02',
    /*LevelCount*/      1)
)
AS SOURCE (
    BuildingId,
    SiteId,
    UniversityName,
    CampusName,
    SiteName,
    BuildingAcronym,
    BuildingName,
    CenterX,
    CenterY,
    Rotation,
    [Length],
    Width,
    Height,
    WallsColor,
    RoofColor,
    LevelCount
)
ON
    TARGET.BuildingId = SOURCE.BuildingId
WHEN NOT MATCHED THEN
    INSERT (
        BuildingId,
        SiteId,
        UniversityName,
        CampusName,
        SiteName,
        BuildingAcronym,
        BuildingName,
        CenterX,
        CenterY,
        Rotation,
        [Length],
        Width,
        Height,
        WallsColor,
        RoofColor,
        LevelCount
    )
    VALUES (
        SOURCE.BuildingId,
        SOURCE.SiteId,
        SOURCE.UniversityName,
        SOURCE.CampusName,
        SOURCE.SiteName,
        SOURCE.BuildingAcronym,
        SOURCE.BuildingName,
        SOURCE.CenterX,
        SOURCE.CenterY,
        SOURCE.Rotation,
        SOURCE.[Length],
        SOURCE.Width,
        SOURCE.Height,
        SOURCE.WallsColor,
        SOURCE.RoofColor,
        SOURCE.LevelCount
    )
WHEN MATCHED THEN
    UPDATE SET
        SiteId = SOURCE.SiteId,
        UniversityName = SOURCE.UniversityName,
        CampusName = SOURCE.CampusName,
        SiteName = SOURCE.SiteName,
        BuildingAcronym = SOURCE.BuildingAcronym,
        BuildingName = SOURCE.BuildingName,
        CenterX = SOURCE.CenterX,
        CenterY = SOURCE.CenterY,
        Rotation = SOURCE.Rotation,
        [Length] = SOURCE.[Length],
        Width = SOURCE.Width,
        Height = SOURCE.Height,
        WallsColor = SOURCE.WallsColor,
        RoofColor = SOURCE.RoofColor,
        LevelCount = SOURCE.LevelCount;
