/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
MERGE INTO ThemePark.BOTemplates AS Target
USING (VALUES
    (/*TemplateID*/      '8eeb5b2a-a1f3-4534-abfd-9706c949509f',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Mesa de Estudio',
     /*DefaultLength*/   1.2,
     /*DefaultWidth*/    0.6,
     /*DefaultHeight*/   0.75,
     /*ColorAmount*/     1,
     /*Color1Name*/      'Estructura',
     /*DefaultColor1*/   '#8B4513',
     /*Color2Name*/      NULL,
     /*DefaultColor2*/   NULL,
     /*Color3Name*/      NULL,
     /*DefaultColor3*/   NULL),

    (/*TemplateID*/      '439abedb-7ad7-43e0-8850-729bcc84ae3b',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Silla de Estudio',
     /*DefaultLength*/   0.5,
     /*DefaultWidth*/    0.5,
     /*DefaultHeight*/   0.85,
     /*ColorAmount*/     1,
     /*Color1Name*/      'Estructura',
     /*DefaultColor1*/   '#000000',
     /*Color2Name*/      NULL,
     /*DefaultColor2*/   NULL,
     /*Color3Name*/      NULL,
     /*DefaultColor3*/   NULL),

    (/*TemplateID*/      '40307123-6dbb-4165-b0e5-4bbc29b962fe',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Estantería',
     /*DefaultLength*/   2.0,
     /*DefaultWidth*/    0.3,
     /*DefaultHeight*/   1.8,
     /*ColorAmount*/     2,
     /*Color1Name*/      'Base',
     /*DefaultColor1*/   '#A0522D',
     /*Color2Name*/      'Estantes',
     /*DefaultColor2*/   '#696969',
     /*Color3Name*/      NULL,
     /*DefaultColor3*/   NULL),

    (/*TemplateID*/      '45d9c8a1-b9d8-4c8e-abcb-39c43cbd5ccb',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Mesa de Conferencias',
     /*DefaultLength*/   3.0,
     /*DefaultWidth*/    1.2,
     /*DefaultHeight*/   0.75,
     /*ColorAmount*/     2,
     /*Color1Name*/      'Superficie',
     /*DefaultColor1*/   '#8B0000',
     /*Color2Name*/      'Patas',
     /*DefaultColor2*/   '#000000',
     /*Color3Name*/      NULL,
     /*DefaultColor3*/   NULL),

    (/*TemplateID*/      '9afe77c2-7b15-4972-ab8d-5d46af76557b',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Sillón',
     /*DefaultLength*/   0.9,
     /*DefaultWidth*/    0.9,
     /*DefaultHeight*/   1.0,
     /*ColorAmount*/     3,
     /*Color1Name*/      'Estructura',
     /*DefaultColor1*/   '#2F4F4F',
     /*Color2Name*/      'Cojines',
     /*DefaultColor2*/   '#8B4513',
     /*Color3Name*/      'Apoyabrazos',
     /*DefaultColor3*/   '#000000'),

    (/*TemplateID*/      '22439e08-86ad-43f0-bec7-615401fde5ec',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Armario de Archivos',
     /*DefaultLength*/   1.0,
     /*DefaultWidth*/    0.5,
     /*DefaultHeight*/   1.8,
     /*ColorAmount*/     3,
     /*Color1Name*/      'Estructura',
     /*DefaultColor1*/   '#2E8B57',
     /*Color2Name*/      'Cajones',
     /*DefaultColor2*/   '#8B4513',
     /*Color3Name*/      'Puertas',
     /*DefaultColor3*/   '#4682B4'),

    (/*TemplateID*/      'ef0aa846-778f-4195-8ca3-9c0127b6160d',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Escultura',
     /*DefaultLength*/   0.6,
     /*DefaultWidth*/    0.6,
     /*DefaultHeight*/   1.5,
     /*ColorAmount*/     1,
     /*Color1Name*/      'Material',
     /*DefaultColor1*/   '#708090',
     /*Color2Name*/      NULL,
     /*DefaultColor2*/   NULL,
     /*Color3Name*/      NULL,
     /*DefaultColor3*/   NULL),

    (/*TemplateID*/      '2f7b1649-f3b5-46a6-8271-52476c4e157c',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Jarrón',
     /*DefaultLength*/   0.2,
     /*DefaultWidth*/    0.2,
     /*DefaultHeight*/   0.5,
     /*ColorAmount*/     1,
     /*Color1Name*/      'Material',
     /*DefaultColor1*/   '#FFD700',
     /*Color2Name*/      NULL,
     /*DefaultColor2*/   NULL,
     /*Color3Name*/      NULL,
     /*DefaultColor3*/   NULL),

    (/*TemplateID*/      '426bddd1-8eff-4df4-9b0e-39066b2c7530',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Lámpara de Pie',
     /*DefaultLength*/   0.3,
     /*DefaultWidth*/    0.3,
     /*DefaultHeight*/   1.5,
     /*ColorAmount*/     2,
     /*Color1Name*/      'Base',
     /*DefaultColor1*/   '#B0C4DE',
     /*Color2Name*/      'Pantalla',
     /*DefaultColor2*/   '#FFFFFF',
     /*Color3Name*/      NULL,
     /*DefaultColor3*/   NULL),

    (/*TemplateID*/      '360570d8-124d-4ec1-b77a-0bbde895a360',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Revistero',
     /*DefaultLength*/   0.4,
     /*DefaultWidth*/    0.3,
     /*DefaultHeight*/   0.6,
     /*ColorAmount*/     2,
     /*Color1Name*/      'Estructura',
     /*DefaultColor1*/   '#DEB887',
     /*Color2Name*/      'Revistas',
     /*DefaultColor2*/   '#FFD700',
     /*Color3Name*/      NULL,
     /*DefaultColor3*/   NULL),

    (/*TemplateID*/      '990804d6-6bbc-40c8-b55f-0d9d90419545',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Reloj de Pie',
     /*DefaultLength*/   0.5,
     /*DefaultWidth*/    0.5,
     /*DefaultHeight*/   1.8,
     /*ColorAmount*/     3,
     /*Color1Name*/      'Estructura',
     /*DefaultColor1*/   '#8B4513',
     /*Color2Name*/      'Manecillas',
     /*DefaultColor2*/   '#000000',
     /*Color3Name*/      'Números',
     /*DefaultColor3*/   '#FFD700'),

    (/*TemplateID*/      'bda5b09a-d037-42f8-86ce-83a2af7e5b6b',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Maceta',
     /*DefaultLength*/   0.4,
     /*DefaultWidth*/    0.4,
     /*DefaultHeight*/   0.8,
     /*ColorAmount*/     3,
     /*Color1Name*/      'Maceta',
     /*DefaultColor1*/   '#D2B48C',
     /*Color2Name*/      'Tierra',
     /*DefaultColor2*/   '#008000',
     /*Color3Name*/      'Planta',
     /*DefaultColor3*/   '#32CD32')
)
AS Source (
    TemplateId, 
    ObjectType, 
    Plane,
    ObjectName, 
    DefaultLength, 
    DefaultWidth, 
    DefaultHeight, 
    ColorAmount, 
    Color1Name, 
    DefaultColor1, 
    Color2Name, 
    DefaultColor2, 
    Color3Name, 
    DefaultColor3
)
ON Target.TemplateId = Source.TemplateId
WHEN MATCHED THEN
    UPDATE SET
        Target.ObjectType = Source.ObjectType,
        Target.Plane = Source.Plane,
        Target.ObjectName = Source.ObjectName,
        Target.DefaultLength = Source.DefaultLength,
        Target.DefaultWidth = Source.DefaultWidth,
        Target.DefaultHeight = Source.DefaultHeight,
        Target.ColorAmount = Source.ColorAmount,
        Target.Color1Name = Source.Color1Name,
        Target.DefaultColor1 = Source.DefaultColor1,
        Target.Color2Name = Source.Color2Name,
        Target.DefaultColor2 = Source.DefaultColor2,
        Target.Color3Name = Source.Color3Name,
        Target.DefaultColor3 = Source.DefaultColor3
WHEN NOT MATCHED THEN
    INSERT (
        TemplateId, 
        ObjectType,
        Plane,
        ObjectName, 
        DefaultLength, 
        DefaultWidth, 
        DefaultHeight, 
        ColorAmount, 
        Color1Name, 
        DefaultColor1, 
        Color2Name, 
        DefaultColor2, 
        Color3Name, 
        DefaultColor3)
    VALUES (
        Source.TemplateId, 
        Source.ObjectType, 
        Source.Plane,
        Source.ObjectName, 
        Source.DefaultLength, 
        Source.DefaultWidth, 
        Source.DefaultHeight, 
        Source.ColorAmount, 
        Source.Color1Name, 
        Source.DefaultColor1, 
        Source.Color2Name, 
        Source.DefaultColor2, 
        Source.Color3Name, 
        Source.DefaultColor3);
