/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
MERGE INTO ThemePark.BuildingObjects AS Target
USING (VALUES
    (/*ObjectId*/        '9ebdbeaf-ed2e-4470-8438-6e476272044a',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Mesa de Estudio',
     /*Length*/          1.2,
     /*Width*/           0.6,
     /*Height*/          0.75,
     /*ColorAmount*/     1,
     /*Color1*/          '#8B4513', 
     /*Color2*/          NULL,
     /*Color3*/          NULL,
     /*CenterX*/         10.0,
     /*CenterY*/         15.0,
     /*Rotation*/        0.0,
     /*LevelId*/         '1b73460c-15bc-4dcf-b1c4-682f4d6f37b2',
     /*WallId*/          NULL),

    (/*ObjectId*/        '2f182eaf-9b53-4bc9-8120-594df4473bdd',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Silla de Estudio',
     /*Length*/          0.5,
     /*Width*/           0.5,
     /*Height*/          0.85,
     /*ColorAmount*/     1,
     /*Color1*/          '#000000', 
     /*Color2*/          NULL,
     /*Color3*/          NULL,
     /*CenterX*/         12.0,
     /*CenterY*/         15.0,
     /*Rotation*/        0.0,
     /*LevelId*/         '1b73460c-15bc-4dcf-b1c4-682f4d6f37b2',
     /*WallId*/          NULL),

    (/*ObjectId*/        '159fd358-ce77-4320-a335-83d72e3565ff',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Estantería',
     /*Length*/          2.0,
     /*Width*/           0.3,
     /*Height*/          1.8,
     /*ColorAmount*/     2,
     /*Color1*/          '#A0522D', 
     /*Color2*/          '#696969', 
     /*Color3*/          NULL,
     /*CenterX*/         5.0,
     /*CenterY*/         7.0,
     /*Rotation*/        0.0,
     /*LevelId*/         '1b73460c-15bc-4dcf-b1c4-682f4d6f37b2',
     /*WallId*/          NULL),

    (/*ObjectId*/        '3c32ad33-135c-46c6-9b83-ccec679c9ba3',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Mesa de Conferencias',
     /*Length*/          3.0,
     /*Width*/           1.2,
     /*Height*/          0.75,
     /*ColorAmount*/     2,
     /*Color1*/          '#8B0000', 
     /*Color2*/          '#000000', 
     /*Color3*/          NULL,
     /*CenterX*/         20.0,
     /*CenterY*/         20.0,
     /*Rotation*/        90.0,
     /*LevelId*/         '1b73460c-15bc-4dcf-b1c4-682f4d6f37b2',
     /*WallId*/          NULL),

    (/*ObjectId*/        '380392d1-4ef6-427d-a16b-239160f3bafe',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Sillón',
     /*Length*/          0.9,
     /*Width*/           0.9,
     /*Height*/          1.0,
     /*ColorAmount*/     3,
     /*Color1*/          '#2F4F4F', 
     /*Color2*/          '#8B4513', 
     /*Color3*/          '#000000', 
     /*CenterX*/         25.0,
     /*CenterY*/         25.0,
     /*Rotation*/        45.0,
     /*LevelId*/         '677ad01f-87f4-4804-8700-84f979afc56e',
     /*WallId*/          NULL),

    (/*ObjectId*/        '21b7b433-0a0a-4110-9980-53d0d57bdde3',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Escultura',
     /*Length*/          0.6,
     /*Width*/           0.6,
     /*Height*/          1.5,
     /*ColorAmount*/     1,
     /*Color1*/          '#708090', 
     /*Color2*/          NULL,
     /*Color3*/          NULL,
     /*CenterX*/         30.0,
     /*CenterY*/         30.0,
     /*Rotation*/        0.0,
     /*LevelId*/         '677ad01f-87f4-4804-8700-84f979afc56e',
     /*WallId*/          NULL),

    (/*ObjectId*/        '688242e8-7fa1-4b36-af5d-f3e62147687f',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Jarrón',
     /*Length*/          0.2,
     /*Width*/           0.2,
     /*Height*/          0.5,
     /*ColorAmount*/     1,
     /*Color1*/          '#FFD700', 
     /*Color2*/          NULL,
     /*Color3*/          NULL,
     /*CenterX*/         35.0,
     /*CenterY*/         35.0,
     /*Rotation*/        0.0,
     /*LevelId*/         '677ad01f-87f4-4804-8700-84f979afc56e',
     /*WallId*/          NULL),

    (/*ObjectId*/        'eda4ac54-c713-42dd-b6e6-df614a3f7c76',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Lámpara de Pie',
     /*Length*/          0.3,
     /*Width*/           0.3,
     /*Height*/          1.5,
     /*ColorAmount*/     2,
     /*Color1*/          '#B0C4DE', 
     /*Color2*/          '#FFFFFF', 
     /*Color3*/          NULL,
     /*CenterX*/         40.0,
     /*CenterY*/         40.0,
     /*Rotation*/        0.0,
     /*LevelId*/         '677ad01f-87f4-4804-8700-84f979afc56e',
     /*WallId*/          NULL),

    (/*ObjectId*/        'de1f359e-7fcc-4e1b-8b2c-cb125a18dcb1',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Revistero',
     /*Length*/          0.4,
     /*Width*/           0.3,
     /*Height*/          0.6,
     /*ColorAmount*/     2,
     /*Color1*/          '#DEB887', 
     /*Color2*/          '#FFD700', 
     /*Color3*/          NULL,
     /*CenterX*/         45.0,
     /*CenterY*/         45.0,
     /*Rotation*/        0.0,
     /*LevelId*/         '4afe2369-6c0a-487c-b3ab-7e8e59117606',
     /*WallId*/          NULL),

    (/*ObjectId*/        '2898e6f9-b6ea-4a09-8bd9-6d13680b1c5c',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Reloj de Pie',
     /*Length*/          0.5,
     /*Width*/           0.5,
     /*Height*/          1.8,
     /*ColorAmount*/     3,
     /*Color1*/          '#8B4513', 
     /*Color2*/          '#000000', 
     /*Color3*/          '#FFD700', 
     /*CenterX*/         50.0,
     /*CenterY*/         50.0,
     /*Rotation*/        0.0,
     /*LevelId*/         '4afe2369-6c0a-487c-b3ab-7e8e59117606',
     /*WallId*/          NULL),

    (/*ObjectId*/        '32a47994-85d0-471a-8b1f-d8701b3a5e39',
     /*ObjectType*/      'Decorativo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Maceta',
     /*Length*/          0.4,
     /*Width*/           0.4,
     /*Height*/          0.8,
     /*ColorAmount*/     3,
     /*Color1*/          '#D2B48C', 
     /*Color2*/          '#008000', 
     /*Color3*/          '#32CD32', 
     /*CenterX*/         55.0,
     /*CenterY*/         55.0,
     /*Rotation*/        0.0,
     /*LevelId*/         '4afe2369-6c0a-487c-b3ab-7e8e59117606',
     /*WallId*/          NULL),

    (/*ObjectId*/        'd9bdea2b-02b4-4c0b-8c26-c64eecce3cce',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Mesa de Estudio',
     /*Length*/          1.5,
     /*Width*/           0.7, 
     /*Height*/          0.75,
     /*ColorAmount*/     1,
     /*Color1*/          '#8B4513',
     /*Color2*/          NULL,
     /*Color3*/          NULL,
     /*CenterX*/         10.0,
     /*CenterY*/         15.0,
     /*Rotation*/        0.0,
     /*LevelId*/         '4afe2369-6c0a-487c-b3ab-7e8e59117606',
     /*WallId*/          NULL),

    (/*ObjectId*/        'efc735cc-90b1-48ad-b5e4-575fd629ca55',
     /*ObjectType*/      'Interactivo',
     /*Plane*/           'Piso',
     /*ObjectName*/      'Silla de Estudio',
     /*Length*/          0.5,
     /*Width*/           0.5,
     /*Height*/          0.85,
     /*ColorAmount*/     1,
     /*Color1*/          '#FF0000',
     /*Color2*/          NULL,
     /*Color3*/          NULL,
     /*CenterX*/         12.0,
     /*CenterY*/         15.0,
     /*Rotation*/        0.0,
     /*LevelId*/         '4afe2369-6c0a-487c-b3ab-7e8e59117606',
     /*WallId*/          NULL)
)
AS Source (
    ObjectId, 
    ObjectType, 
    Plane,
    ObjectName, 
    [Length], 
    Width, 
    Height, 
    ColorAmount,
    Color1, 
    Color2, 
    Color3, 
    CenterX, 
    CenterY, 
    Rotation, 
    LevelId,
    WallId
)
ON Target.ObjectId = Source.ObjectId
WHEN MATCHED THEN
    UPDATE SET
        Target.ObjectType = Source.ObjectType,
        Target.Plane = Source.Plane,
        Target.ObjectName = Source.ObjectName,
        Target.[Length] = Source.[Length],
        Target.Width = Source.Width,
        Target.Height = Source.Height,
        Target.ColorAmount = Source.ColorAmount,
        Target.Color1 = Source.Color1,
        Target.Color2 = Source.Color2,
        Target.Color3 = Source.Color3,
        Target.CenterX = Source.CenterX,
        Target.CenterY = Source.CenterY,
        Target.Rotation = Source.Rotation,
        Target.LevelId = Source.LevelId,
        Target.WallId = Source.WallId
WHEN NOT MATCHED THEN
    INSERT (
        ObjectId, 
        ObjectType, 
        Plane,
        ObjectName, 
        [Length], 
        Width, 
        Height, 
        ColorAmount,
        Color1, 
        Color2, 
        Color3, 
        CenterX, 
        CenterY, 
        Rotation, 
        LevelId,
        WallId)
    VALUES (
        Source.ObjectId, 
        Source.ObjectType, 
        Source.Plane,
        Source.ObjectName, 
        Source.[Length], 
        Source.Width, 
        Source.Height, 
        Source.ColorAmount,
        Source.Color1, 
        Source.Color2, 
        Source.Color3, 
        Source.CenterX, 
        Source.CenterY, 
        Source.Rotation, 
        Source.LevelId,
        Source.WallId);
